dist: trusty
sudo: required
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "yTKGeg0/BNIJzE7UJm7sNvSnvHBcf2wKo/lwvFrQbKrKCBMP92mD68R7Clf8ckt76g+J+TGHoW0DuxlRS8xBpuMhHW7ocG50R+YynTZVWJfhOwLvaGfzZJPXpJANToouT9NqLeDp2TzUpm4X+A5s7
nxLk9JblGU9POMAWklXCw6+3lb1K4Hf31CR2HRRV5oi2GokMFBQKNR2fcDHg2e9cheV/c3NLmn936e858HRlSq9IOQR8qlM8UsB+Qci6sQ67MHkvGflLwcDnH5FxvsK9CsdEJUu5asycsgLdm4O/RJJ/1zgPz0RI
21dtsHVeTu3eBYgtbvdYmyDu2/PNxnko4OUkB8AD4hmWZLgeOn/W7A9wNbA1aC650zQR5mCS6DgLs8b7RTSKTzw1HnItuINKOIsPmWeQSDmjt66dWe9tETR5CTiJ2/YVbmvmCXRS6HN8gkevGm5P/JAjP9vjBdcm
/AQ+MsnxjxzNictJCyjbzfWx9mczDIv925bFiKidG9AaAiBdpaoNisB/SeiioeSH25dNt2FUcSdlYjianmcaTtoidHDO4QLzVsy6puJSt0Poauln1/wivvlRxVA4AQlxZuSD6QuYQt/LaJ6J6mTlo6p3Hn9tcfnI
iDFdPKTsMVS9Rx5AzdfLy7/z1sZEayGFmXqlGwKOwyRk7mkIGubfxM="

addons:
  sonarcloud:
    organization: "toop4eu"
    token:
      secure: "dyzNSK1v/A8Us+XajZhPEN+CVAfskXBpKXxLKEzgASLnxQc0z2rM4/968n9WvLli1zpfyGIflbcnLWYdH05sdjnxVATLKkD+sjQFCkcdJ3qo+ZrpxTJAreUOVjBl3t9579xe7x2mpclV2099ZOB1z
zk+LoPyf8m56UoVxkOVcttf9Jjj+EDaXze7nkcj0yeS6EpJmcTT4aTLErNIa8A1pyn6RQUQAgn2aeHboU+D7ALXtrPpvnKIZJGWgXZEHjy7Ws3dNXq4g2vQESnBlb5dzuQ6HCQwFHC2il7t2qhZhDw0YkY6U96yD
Jod3jdMg64YEoUOYvvLNNSeevyVB3o766KfMo2/JgZCvDev6YOXXZCCaAu03uS+2YhEsrQGe3z6HVKjfKBVzxAc3ymvheXFVGE/kE+Ct0XrBf0IzODJD7Pad9zhPhfGMLC/N/URn3pD/PgMjVOhntQVyIdOI+pzI
VDKetwV7DMY6XpujKUuEwRpnMS8FfwbXfnObYVjE+HxZBmMgEYh6awld7DtHBGVXgAqF6mRznCdgTnDhlQO6i9mlWuA9UlaeYSVtd0ajMSOyHu9DBNACHdGYtne+N3d8fVkueL3j2s/1xmJS5R8XRfRaDh5E1U3M
3fBv0auJ+6L/KUD7Z12EMEPFnMj1P62QcDuvW2NqLJvw/x61CnqWNw="
   
jdk:
  - oraclejdk8
  
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps

script:
  -  mvn test -B -P coverage sonar:sonar
  
cache:
  directories:
    - $HOME/.m2

after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
  - bash <(curl -s https://codecov.io/bash)
